name: Resharper Code Analysis
 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
               
      - name: Run resharper inspection
        run: jb inspectcode AssistPurchase.sln /output=insreport.xml
   
      - name: Run resharper duplicate code check
        run: jb dupfinder AssistPurchase.sln /output=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1